In [77]:
import numpy as np
import pandas as pd

In [79]:
data = [
[2001,"C101","2023-08-01 18:00","2023-08-01 18:45",500,"upi","Dominos",4],
[2002,"C102","2023-08-01 19:00","2023-08-01 18:50",700,"Credit card","KFC",5],
[2003,"C103","2023/08/02 20:00",None,None,"Debit Card","McDonalds",3],
[2004,"C104","invalid","2023-08-03 21:00",800,"UPI","Dominos",6],
[2005,"C105","2023-08-04 18:30","2023-08-04 19:00",-200,"Cash","KFC",2],
[2005,"C105","2023-08-04 18:30","2023-08-04 19:00",-200,"Cash","KFC",2],
[2006,"C106","2023-08-05 17:00","2023-08-05 17:40",1200,None,"Pizza Hut",4]
]

columns = ["order_id","customer_id","order_time","delivery_time","order_value","payment_method","restaurant","rating"]

df = pd.DataFrame(data, columns=columns)
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00,2023-08-01 18:45,500.0,upi,Dominos,4
1,2002,C102,2023-08-01 19:00,2023-08-01 18:50,700.0,Credit card,KFC,5
2,2003,C103,2023/08/02 20:00,None,NaN,Debit Card,McDonalds,3
3,2004,C104,invalid,2023-08-03 21:00,800.0,UPI,Dominos,6
4,2005,C105,2023-08-04 18:30,2023-08-04 19:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30,2023-08-04 19:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00,2023-08-05 17:40,1200.0,None,Pizza Hut,4

In [81]:
#Cleaning
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        7 non-null      int64
 1   customer_id     7 non-null      object
 2   order_time      7 non-null      object
 3   delivery_time   6 non-null      object
 4   order_value     6 non-null      float64
 5   payment_method  6 non-null      object
 6   restaurant      7 non-null      object
 7   rating          7 non-null      int64
dtypes: float64(1), int64(2), object(5)
memory usage: 580.0+ bytes
None

In [83]:
print(df.isnull().sum)

<bound method DataFrame.sum of    order_id  customer_id  order_time  delivery_time  order_value  \
0     False        False       False          False        False
1     False        False       False          False        False
2     False        False       False           True         True
3     False        False       False          False        False
4     False        False       False          False        False
5     False        False       False          False        False
6     False        False       False          False        False

   payment_method  restaurant  rating
0           False       False   False
1           False       False   False
2           False       False   False
3           False       False   False
4           False       False   False
5           False       False   False
6            True       False   False  >

In [85]:
print(df.duplicated().sum())

1

In [87]:
#1Fix date and time coluumns
df['order_time'] = pd.to_datetime(df['order_time'], errors='coerce')
df['delivery_time'] = pd.to_datetime(df['delivery_time'], errors='coerce')

In [89]:
# Remove inalid rec
#drop - only few null or fill - mostly null

#Drop rows where order_time and del time is missing
#df = df[df['order_time'].dropna()]



#df = df[df['delivery_time'].dropna()]

#OR

df = df.dropna(subset=['order_time','delivery_time'])

df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
1,2002,C102,2023-08-01 19:00:00,2023-08-01 18:50:00,700.0,Credit card,KFC,5
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,None,Pizza Hut,4

In [91]:
#2remove rows where deltime is before order
df = df[df['delivery_time'] >= df['order_time']]
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,None,Pizza Hut,4

In [99]:
#4Handling incorrect val
df = df[df['order_value'] > 0]


#fill missing val
df['payment_method'].fillna('unknown',inplace = True)

C:\Users\aksha\AppData\Local\Temp\ipykernel_19712\1333610667.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['payment_method'].fillna('unknown',inplace = True)

In [101]:
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,unknown,Pizza Hut,4

In [103]:
#5
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,unknown,Pizza Hut,4

In [107]:
df.drop_duplicates(inplace=True)

In [113]:
#6
df['payment_method'] = df['payment_method'].str.upper()

df['restaurant']=df['restaurant'].str.title()
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,UPI,Dominos,4
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,UNKNOWN,Pizza Hut,4

In [123]:
#validation checks
assert df.duplicated().sum()==0
assert (df['order_value']>0).all()

In [125]:
df.to_csv("orders_food_cleaned.csv",index=False)